### PR TITLE
sync apis

### PR DESCRIPTION
**Pull request by 27149chen**
sync apis

### CODE REVIEW

**Comment by Iceber** [comment]
@27149chen Thanks for your contribution.

[v1alpha2/zz_generated.deepcopy.go](https://github.com/clusterpedia-io/clusterpedia/blob/6b0f33bb8455d678ec65cb44f1b2f5347a69c770/pkg/apis/cluster/v1alpha2/zz_generated.deepcopy.go) should also need to be synced.

> ref pr: https://github.com/clusterpedia-io/clusterpedia/pull/115

**Comment by 27149chen** [comment]
updated

**Review by Iceber — APPROVED** [review]
LGTM

**Comment by calvin0327** [comment]
/lgtm
@27149chen Thanks for your pr. 🎉

**Pull request merged**
