### PR TITLE
update go.mod

### PR DESCRIPTION
**Pull request by huoyinghao**
update go.mod k8s version to 0.25.3
update go.mod sigs.k8s.io/controller-runtime to v0.13.0
update go version to 1.18

### CODE REVIEW

**Comment by calvin0327** [comment]
It's like good to me.

/lgtm

**Comment by calvin0327** [comment]
https://github.com/clusterpedia-io/client-go/tree/main/examples

We can test thoes example whether is running properly?

**Comment by huoyinghao** [comment]
@calvin0327 
https://github.com/clusterpedia-io/client-go/tree/main/examples
3个样例全都跑起来了

**Comment by huoyinghao** [comment]
https://github.com/clusterpedia-io/client-go/issues/54
https://github.com/clusterpedia-io/client-go/issues/52

**Comment by Iceber** [comment]
The 1.25 dependency requires a minimum golang version of 1.19

example: https://github.com/kubernetes/client-go/blob/master/go.mod

**Comment by huoyinghao** [comment]
@Iceber 
好的,我把go版本升级到1.19

**Comment by calvin0327** [comment]
@huoyinghao thanks.

**Pull request merged**
